### ISSUE TITLE
minimap2 as alternative alignment tool

### ISSUE THREAD

**Issue by silenus092** [rki-mf1/covsonar#10]
In GitLab by @hoelzer on May 27, 2021, 09:54

Could be interesting to test `minimap2` as aligner instead of `EMBOSS-stretcher` 

E.g. the developer just announced that

> Minimap2 v2.19 released with better and more contiguous alignment over long INDELs and in highly repetitive regions, improvements backported from unimap. These represent the most significant algorithmic change since v2.1. Use with caution.

https://twitter.com/lh3lh3/status/1397736460174888961?s=19

I would be interested in how well `minimap2` is able to accurately align genomes over long N stretches.

**Comment by stephan-fuchs** [comment]
Minimap2 was excluded from our selection of tools as it does not provide global alignment. However, in CovSonar2 (https://github.com/rki-mf1/covsonar/tree/dev/covsonar2-alpha), we use semi-global alignment provided by PARASAIL which produces optimal results.
