### ISSUE TITLE
feature wishlist (please add)

### ISSUE THREAD

**Issue by silenus092** [rki-mf1/covsonar#13]
In GitLab by @s.fuchs on Jun 3, 2021, 07:45

For the next feature updates, I wolud like to collect here some points. Feel free to add your suggestions!

- [x] gz/xz input file support when adding fasta and metadata
- [x] country metadata field
- [x] age metadata field
- [ ] stats about blind spots (N) when matching genomic profiles
- [x] tsv output option
- [x] paranoid test optional
- [x] code improvements for easier metadata set extensions
- [ ] Workflow diagram + FAQ to README
- [x] Host info.(covv_host) from gisaid (Host column in GenomeTable)
- [x] Now It is time for the sublinage command `--sub-linage` https://gitlab.com/s.fuchs/covsonar/-/issues/17

**Comment by MarieLataretu** [comment]
Hi all,

the options `--only_frameshifts` and `--no_frameshifts` would be cool for covsonar2.
They work in version <2 , but are not implemented yet for version 2 as far as I know!

**Comment by matthuska** [comment]
I'm going to move the remaining features in this to individual issues so they can be managed better, and then close this meta issue. Please create a new issue with any feature requests and add the label "feature request".

**Comment by matthuska** [comment]
All issues in this meta issue should have their own single issues now. Please add new ones if I've missed anything.
