### ISSUE TITLE
frameshifts stay undetected

### ISSUE THREAD

**Issue by silenus092** [rki-mf1/covsonar#15]
In GitLab by @oliverdrechsel on Jun 22, 2021, 09:38

it seems a few frameshift variants that are detected by GISAID stay unnoticed by covsonar (or i used it wrong).

```
tools/covsonar/sonar.py  --version
sonar.py 1.1.0
```

i used an earlier upload from desh to GISAID. The GISAID rejected IDs were kept and fasta file filtered accordingly.

```
seqkit grep -f 03-reporting/rejected.rki.ids 02-to-upload/gisaid.renamed.fasta > 05-tool_check/gisaid.rejected.fasta
time ../tools/covsonar/sonar.py add --db gisaid.rejected.db --file gisaid.rejected.fasta --cpus 30 &> gisaid.rejected.2covsonar.log
```

selecting for sequences with no detected frameshifts brings up the following list ... full IDs are in the folder, which I'd send via mail

```
../tools/covsonar/sonar.py match --db gisaid.rejected.db --no_frameshifts > covsonar.noframeshift.csv
```

i erased the SNVs to give the genomes some privacy.

variants that look suspicious to me are highlighted with >>...<<

```
$ cut -f19 -d, covsonar.noframeshift.csv | less

dna_profile
[...] >>T22204TACAGATCGA<< [...] del:25446:30 [...] >>del:28271:2<< [...]
>>del:1:25<< [...] del:15430:120 [...] del:21765:6 [...] >>del:29539:37<< [...] >>del:29848:53<< [...]
[...] >>T22204TACAGATCGA<< [...] del:25446:30 [...] >>del:28271:2<< [...]
[...] >>T22204TACAGATCGA<< [...] del:25446:30 [...] >>del:28271:2<< [...]
>>del:1:31<< [...] >>del:28271:2<< [...] >>del:29714:190<<
[...] del:11288:9 [...] >>T22204TACAGATCGA<< [...] del:25446:30 [...] >>del:28271:2<< [...]

```

**Comment by stephan-fuchs** [comment]
CovSonar2 introduces improved variant calling and frameshift detection capabilities. You can check it out here: https://github.com/rki-mf1/covsonar/tree/dev/covsonar2-alpha
