### ISSUE TITLE
We need to talk about deletions ...

### ISSUE THREAD

**Issue by silenus092** [rki-mf1/covsonar#24]
In GitLab by @hoelzer on Jan 18, 2022, 13:02

... this is a general problem. It happens quite often, that we search for certain deletions reported in the literature but can not be certain that these are located at the same position in covsonar: likely due to the way alignments of deletions are oriented.

For example:

del69/70 is commonly know from Alpha, Omicron, ... but in our covsonar databases stored as `S:del:68:3` which then need to be used to find the deletion. 

The same holds for `S:del:244:2` (present in Beta and reported at this site), which is actually present as `S:del:240:4` in covsonar.
@spsofia 

How can we deal with that in the future? Should covsonar at least provide a warning when deletions are searched?

**Comment by stephan-fuchs** [comment]
Thank you very much for bringing up this important point. I wanted to let you know that CovSonar2, which is currently in its alpha stage, supports both greedy and ungreedy deletion matching. If you are interested in trying out this version, you can find it here: https://github.com/rki-mf1/covsonar/tree/dev/covsonar2-alpha
