### ISSUE TITLE
Information on NNNNN stretches

### ISSUE THREAD

**Issue by hoelzer** [rki-mf1/covsonar#53]
When just looking at the mutation profile output from CovSonar this can be misleading if the user does not check fo regions that are actually masked by NNNNs (amplicon drop, low coverag). For example, the user might then think that a certain lineage has reverted some of the characteristic mutations but actually they can just not be called because there is no information available at that genome position.

Suggestion: can covSonar add information on NNNN stretches to the output? So that on could easily see which regions (start-stop) of a genome are masked by NNNs and can thus not be used to call variants?

**Comment by stephan-fuchs** [comment]
Thank you for bringing this issue to our attention. Currently, you can use the --ambig parameter to include ambiguous mutations in the genome profiles that are returned. While we will continue to explore potential improvements in this area, it may be challenging to provide N-stretch information for all mutations of complex profiles in a clear and understandable format.
