### ISSUE TITLE
Decrease memory usage when outputting mutation profiles from large databases

### ISSUE THREAD

**Issue by matthuska** [rki-mf1/covsonar#54]
Outputting a TSV with the DNA profiles of the current full GISAID database requires > 100GB of RAM. This should be reduced to make the tool usable by people with more modest computing resources.

**Comment by stephan-fuchs** [comment]
Thank you for your feedback! We are currently working on CovSonar2, which is now in its alpha stage (https://github.com/rki-mf1/covsonar/tree/dev/covsonar2-alpha). We have made significant improvements to its resource management. However, please note that some operations, such as generating VCF output, still require loading the full result set into memory for data transfomation.
