### ISSUE TITLE
Allow to select output columns

### ISSUE THREAD

**Issue by silenus092** [rki-mf1/covsonar#72]
Thank you @matthuska

It could be nice if covSonar could allow users to select output columns; for example, 
```
sonar match --profile S:K418x --db test.db  -o out.csv  --output-column accession,dna_profile
```

 tag and column name separated by comma **--output-column accession,dna_profile**

**Comment by silenus092** [comment]
Added in PR #73

**Comment by matthuska** [comment]
Nice, this will be very useful. Thanks!
