### ISSUE TITLE
--platform not working

### ISSUE THREAD

**Issue by AliceWi** [rki-mf1/covsonar#74]
Hey guy, I just noticed that the platform filter does not work.

```
sonar.py match -db db --date 2021-02-01:2022-08-31 --platform xyz --count 
```
returns 16, but it should return 0, since all entries in platform for this selection are empty.

**Comment by silenus092** [comment]
Hi @AliceWi 

Thank you for your ticket.

This issue is solved PR #75 (512f8a6) and I made a new release[  v1.1.7 ](https://github.com/rki-mf1/covsonar/releases/tag/v1.1.7)

please update the latest version and let me know if the problem is solved or not
