### ISSUE TITLE
Update of a sequence identical to another deletes mutation profile of the other sequence

### ISSUE THREAD

**Issue by paulwolk** [rki-mf1/covsonar#80]
1) Have to exactly identical sequences <1> & <2> with mutations in the database.
2) Sequence <2> gets an update and has a new sequence, so I add it with the "force" flag to overwrite the old sequence.
3) <2> is correctly updated now, but <1> has an empty mutations field.

This is for the current version 1.1.8.

**Comment by MarieLataretu** [comment]
It seems like the bug was introduced after version 1.1.7

```bash
git clone https://github.com/rki-mf1/covsonar.git
cd covsonar
sonar.py --version
# 1.1.8
# bug
```

```bash
git clone -b v1.1.7 https://github.com/rki-mf1/covsonar.git
cd covsonar
sonar.py --version
# 1.1.7
# no bug
```

**Comment by stephan-fuchs** [comment]
We have resolved the issue you reported and incorporated the fix into our latest Alpha Version of covSonar 2. You can find the updated version at https://github.com/rki-mf1/covsonar/tree/dev/covsonar2-alpha. We encourage you to try it out and let us know your feedback. Thank you for your support and contribution to the development of covSonar.

**Comment by matthuska** [comment]
covsonar 1 is still being used and this is still not resolved in the latest covsonar 1.x release. I'm reopening this and will write a PR with a fix.
