### ISSUE TITLE
Match accessions by list of accessions in a file

### ISSUE THREAD

**Issue by MarieLataretu** [rki-mf1/covsonar#90]
Hey there,

It would be wonderful to have the option to match multiple accession IDs from a list:
```
path/to/covsonar/sonar.py match --acc --file myids.txt
```
with one accession per line in `myids.txt`.

Cheers
Marie

**Comment by matthuska** [comment]
I think this has been requested a bunch of times already and I agree that it'd be useful. We'll see about the exact syntax, but it'll be documented.

**Comment by matthuska** [comment]
Closed by #123
