### ISSUE TITLE
Explain differences in DNA, AA and frameshift profiles between covsonar 1 and covsonar 2

### ISSUE THREAD

**Issue by matthuska** [rki-mf1/covsonar#97]
Before making covsonar 2 the stable release, we need to be certain that the mutation profiles that both tools produce are either the same, or that the differences can be explained and that covsonar 2 gives "better" profiles.

# Intentional differences between covsonar 1 and covsonar 2:

## Deletions: representation

covsonar 1: `del:28363:8` (last number is the deletion length)
covsonar 2: `del:28363-28371` (last number is end position of the deletion)

## Deletions: left vs. right

covsonar 1: `del:28363-28370`
covsonar 2: `del:28362-28369`

# Unexplained differences between covsonar 1 and covsonar 2:

- [x] Only in covsonar 2 output, but in many sequences: T22204TNNNNNNNNN
- [x] Some deletions and mutations near the beginning or end of the sequence are only in covsonar 1 output: e.g. del:3-44, A1T, del:21-27, del:29838-29903
- [x] covsonar 1: G28882AC -> covonsar 2: T28879TA + G28882C (I think @stephan-fuchs explained that the second case is better because a changed base and an insertion happening in one step is not likely, as is shown in covsonar 1)

**Comment by stephan-fuchs** [comment]
Differences have been now explained in https://github.com/rki-mf1/covsonar/blob/dev/covsonar2-alpha/faq.md

**Comment by matthuska** [comment]
Looks good. If someone finds a new difference they can create a new issue.

We should add a link to the FAQ to the README. I can do that.
